site_name: Daud Kresna
nav:
    - Home: index.md
    - Menghitung Jarak antar Data tipe Numerik: jarak-data.md
# theme: readthedocs
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust